version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--prefix=/jenkins" # http://localhost:8080/jenkins use this for browse
    networks:
      - jenkins_network

  # Docker-in-Docker alternative for Windows
  docker-dind:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    restart: always
    volumes:
      - jenkins_docker_certs:/certs/client
      - jenkins_home:/var/jenkins_home
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      - jenkins_network

volumes:
  jenkins_home:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/jenkins_home'
  jenkins_docker_certs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/jenkins_docker_certs'

networks:
  jenkins_network:
    driver: bridge